(define (make-rand)
  (define x 10)
  (lambda (op)
    (cond ((eq? op 'generate)
	 ((lambda ()
	 (set! x (random x))
	 x)))
	((eq? op 'reset)
	 (lambda (val)
	   (display x)
;	   (set! x val)
;	   (display x)
	   (set! x val)
	   (display x)))
	(else (error "either generate or reset are accepted!")))))

(define rand (make-rand))
